//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_PhamThanhDat_2210900007_Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTDBaoTri
    {
        public int PTDThietBiID { get; set; }
        public Nullable<System.DateTime> PTDNgayBaoTri { get; set; }
        public string PTDMoTaBaoTri { get; set; }
        public Nullable<decimal> PTDChiPhi { get; set; }
        public string PTDNguoiThucHien { get; set; }
    
        public virtual PTDTrangTB PTDTrangTB { get; set; }
    }
}
