//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_PhamThanhDat_2210900007_Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTDLichSuDung
    {
        public int ID { get; set; }
        public Nullable<int> PTDThietBiID { get; set; }
        public Nullable<int> PTDNguoiDungID { get; set; }
        public Nullable<System.DateTime> PTDNgaySuDung { get; set; }
        public string PTDMucDichSuDung { get; set; }
    
        public virtual PTDNguoiDung PTDNguoiDung { get; set; }
        public virtual PTDTrangTB PTDTrangTB { get; set; }
    }
}
