//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_PhamThanhDat_2210900007_Project3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class K22CNT2_PhamThanhDat_Project3Entities : DbContext
    {
        public K22CNT2_PhamThanhDat_Project3Entities()
            : base("name=K22CNT2_PhamThanhDat_Project3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PTDBaoTri> PTDBaoTri { get; set; }
        public virtual DbSet<PTDLichSuDung> PTDLichSuDung { get; set; }
        public virtual DbSet<PTDNguoiDung> PTDNguoiDung { get; set; }
        public virtual DbSet<PTDQuanTri> PTDQuanTri { get; set; }
        public virtual DbSet<PTDTrangTB> PTDTrangTB { get; set; }
    }
}
