//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_PhamThanhDat_2210900007_Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTDQuanTri
    {
        public string PTDTaikhoan { get; set; }
        public Nullable<byte> PTDTrangthai { get; set; }
    }
}
