//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_PhamThanhDat_2210900007_Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTDTrangTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PTDTrangTB()
        {
            this.PTDLichSuDung = new HashSet<PTDLichSuDung>();
        }
    
        public int ID { get; set; }
        public string PTDTenThietBi { get; set; }
        public string PTDAnh { get; set; }
        public string PTDMoTa { get; set; }
        public Nullable<int> PTDSoLuong { get; set; }
        public string PTDTinhTrang { get; set; }
        public Nullable<System.DateTime> PTDNgayBaoTriTiepTheo { get; set; }
    
        public virtual PTDBaoTri PTDBaoTri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PTDLichSuDung> PTDLichSuDung { get; set; }
    }
}
